### ISSUE TITLE
Prep for dr17

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#15]
Hi @havok2063,

I need to have tree/dr17 so I can generate the eboss specobjall file.  I added a stub for dr17.cfg (which is fine for now until we have new vacs) and a bin script to support old IDL code that depends on it.  I installed from master at Utah to confirm it works, and if you want a new tag you can make one, and I'll install from that.

Thanks,
Joel

**Comment by havok2063** [comment]
Hi @joelbrownstein, the recommended procedure is to make changes and prepare updates in a branch, and when you're ready to submit a PR for review.  Once the PR is approved we merge the changes back into `master` and tag.  Since we have a relatively empty dr17 config, can you create a new `dr17` branch off of `master` so we can keep track of related changes?

**Comment by joelbrownstein** [comment]
That makes sense, will do!
