### ISSUE TITLE
Cleanup old branches and configs

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#57]
@havok2063 

Perhaps after tagging tree (as a final SDSS-IV release), a few items in tree should be cleaned up, especially to support the bridge between sdss_access paths and the ICDB access database:
- Remove sdsswork and mpl cfg files, particularly since mangawork, apogeework, ebosswork no longer exist on the SAS
- Delete any branches that are not used, including the sdss5 branch -> main.

**Comment by havok2063** [comment]
It's easy enough to clean up the old branches.  Do you want to also remove the `sdss5` branch?  I think  if we do that, we need to make sure that those branches aren't being used at Utah, and make it clear to people, that if they are to add new paths for sdss5, they will need to create a new branch and make a pull request, rather than committing directly to `main`.  Unless we're forcing everyone to go through your new web form.  In that regard, I might be inclined to add branch protections on tree to `main`, so no one can commit to it.  

I'm a bit more worried about removing the configs for `sdsswork` and the mpls.  This will break lots of downstream codes, tests, webapps, etc, especially removing `sdsswork`.  Are we also migrating the `sdss5` config to `sdsswork`?   If we're committing to doing these things, then I'd sort of like a roadmap of everything that needs updating before we do this.

**Comment by havok2063** [comment]
If we're doing this, this also might be a good time to rename `master` to `main`.

**Comment by joelbrownstein** [comment]
As agreed to on the data telecon, action items include:

1. rename master to main
2. merge sdss5 -> main and delete sdss5 branch
3. protect main
4. only the main branch will be installed at Utah, via sdssunit
5. delete bosswork.cfg, mpl*.cfg, sdsswork.cfg from the data directory
6. rename sdss5.cfg -> sdsswork.cfg; but add a symlink pointing sdss5.cfg -> sdsswork.cfg
