### ISSUE TITLE
repeated allCal

### ISSUE THREAD

**Issue by blanton144** [sdss/tree#7]
There are now two entries for allCal in sdss_paths.ini

I think Jon H introduced the new one:
  allCal = $APOGEE_REDUX/{apred}/allCal.fits

I will update to keep just this one. Jon can complain if that is wrong!

**Comment by blanton144** [comment]
OK, I updated the product, but I think somebody needs to update the version at Utah. Right now this error makes it impossible to use tree at Utah.

**Comment by joelbrownstein** [comment]
try it now, please

**Comment by joelbrownstein** [comment]
Oh wait, Brian broke it.

$ sdss_install tree master -G  -F
/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/sdss_install/master/python/sdss_install/__init__.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(open(os.path.dirname(__file__) + '/etc/{0}.yml'.format(NAME)))
sdssinstall - INFO - Preparing to install in /uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/master (overwriting due to force option)
sdssinstall - INFO - Running command: git clone https://github.com/sdss/tree.git tree-master
sdssinstall - INFO - Completed GitHub clone of repository tree
sdssinstall - INFO - Installing in /uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/master
sdssinstall - INFO - Running "make" in /uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/master
sdssinstall - ERROR - Error during compile:
sdssinstall - ERROR - make[1]: ../bin/sas_base.sh: Command not found
make[1]: ../bin/install_tree.py: Command not found
make[1]: *** [all] Error 127
make: *** [all] Error 2

sdssinstall - INFO - Fail!

**Comment by joelbrownstein** [comment]
Brian and I slacked about the script sdss_install needs for tree, and he's looking at doing the fix now.

**Comment by havok2063** [comment]
Since this is a `sdss_install` and not a `tree` issue, I've created an issue over there, https://github.com/sdss/sdss_install/issues/9, to represent this bug.  Updates to the install issue will be placed there.  

As for the `allCall` duplicate, just a note here we'll need to keep track of the old definition as we transition to the versioned tree.

**Comment by havok2063** [comment]
The `sdss_install` has been fixed.  Please see https://github.com/sdss/sdss_install/issues/9 for comments.  Closing this issue since the `allCal` issue has been resolved.

**Comment by joelbrownstein** [comment]
Tree is now updated at Utah.
