### ISSUE TITLE
apogee new for dr10, not basework

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#8]
there was nothing for apogee in tree prior to dr10, so could we remove

```
[APOGEE]
APOGEE_ROOT = %(FILESYSTEM)s/%(name)s/apogee
APOGEE_DATA = %(APOGEE_ROOT)s/spectro/data
APOGEE_DATA_1M = %(APOGEE_ROOT)s/spectro/data1m
APOGEE_REDUX = %(APOGEE_ROOT)s/spectro/redux
APOGEE_QUICK = %(APOGEE_ROOT)s/spectro/quickred
APOGEE_TARGET = %(APOGEE_ROOT)s/target
```
from basework.cfg?

**Comment by havok2063** [comment]
The DR cfg files do not inherit from `basework.cfg`.  `basework.cfg` is only for the `xxxwork.cfg`.   And APOGEE paths don't enter into DR config files until `dr10.cfg`.  

Regarding `basework` in general, I'd like to keep `basework` because I can see creating different `xxxwork.cfg` perhaps for different SDSS phases or "legacy" work.  And turn `basework` into a bonafide base containing paths that persisted across all phases, e.g.

**Comment by havok2063** [comment]
I think this question has been addressed.  Closing this.
